[package]
name = "nostr-sqlcipher"
version = "0.29.0"
edition = "2021"
description = "SQLCipher Storage backend for Nostr apps"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
keywords = ["nostr", "database", "sqlite"]

[dependencies]
async-trait.workspace = true
deadpool-sqlite = "0.7"
nostr = { workspace = true, features = ["std"] }
nostr-database = { workspace = true, features = ["flatbuf"] }
rusqlite = { version = "0.30", features = ["bundled-sqlcipher"] }
thiserror.workspace = true
tokio = { workspace = true, features = ["sync"] }
tracing = { workspace = true, features = ["std", "attributes"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }
tracing-subscriber.workspace = true
